title: "pto8913"
author: "pto8913"
description: "制作物や知見を置いていく場所"
permalink: /:title/
lang: "jp"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

twitter_username: "pitodesu"
github_username: "pto8913"
resetURL: "https://pto8913.github.io/pto8913"
KyoProURL: "https://pto8913.github.io/pto8913/KyoPro"
PyQtURL: "https://pto8913.github.io/pto8913/PyQt5"
UEURL: "https://pto8913.github.io/pto8913/UE4"
HoshimoriURL: "https://pto8913.github.io/pto8913/Hoshimori"

markdown: CommonMarkGhPages

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
future: true
published: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
 - {file: "index.md"}
 - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
 - {title: Mail, icon: envelope, url: "mailto:pto8913project@gmail.com"}
 - {title: Github, icon: github, url: "https://github.com/pto8913"}
 - {title: Subscribe, icon: rss, url: "/feed.xml"}

# Build settings

plugins:
 - jekyll-feed