# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#encoding: utf-8

title: pto8913
author: pto8913
#email: your-email@example.com
#>- # this means to ignore newlines until "baseurl:"
description: 制作物や知見を置いていく場所
twitter_username: pitodesu
github_username: pto8913


lang: "jp"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

markdown: kramdown

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
future: true
published: true

permalink: /:categories/:title.html
permalink_pattern: /:dir/:categories/:title.html

homeURL: "/home.html"
baseURL: "https://pto8913.github.io/pto8913/home.html"
KyoProURL: "https://pto8913.github.io/pto8913/KyoPro"
PyQtURL: "https://pto8913.github.io/pto8913/PyQt5"
UEURL: "https://pto8913.github.io/pto8913/UE4"
HoshimoriURL: "https://pto8913.github.io/pto8913/Hoshimori"

github: [metadata]
repository: pto8913.github.io/pto8913

# Build settings
# remote_theme: niklasbuschmann/contrast
theme: minima
highlighter: rouge
#theme: jekyll-theme-architect

paginate: 5
paginate_path: "/pto8913/page:num/"


plugins:
  - jekyll-feed
  # - jekyll-remote-theme
  #- jekyll-github-metadata

# Menu

# Navigations
nav-header:                # accepts {file, title, url, icon, sidebaricon}
  ホーム: "/home.html"
  カテゴリ:
    UnrealEngine: "/Portfolio/UnrealEngine/index.html"
    DirectX: "/Portfolio/DirectX/index.html"
    Unity: "/Portfolio/Unity/index.html"
    Java: "/Portfolio/Java/index.html"

  # ポートフォリオ: "/Portfolio/index.html"

nav-footer:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Gmail, icon: '/assets/images/gmail.png', url: "mailto:pto8913project@gmail.com"}
  - {title: Github, icon: '/assets/images/github.png', url: "https://github.com/pto8913"}
  - {title: HatenaBlog, icon: '/assets/images/hatenablog.png', url: "https://pto8913.hatenablog.com/"}
  - {title: Youtube, icon: '/assets/images/youtube.png', url: "https://www.youtube.com/@pto8913/featured"}
  - {title: Discord, icon: '/assets/images/discord.png', url: "https://discord.gg/mXntvZdCFf"}

# NOTE: children allowed only url, contents, title.
nav-categories:
  UnrealEngine: 
    url: "/Portfolio/UnrealEngine/UnrealEngine_Index.html"
    contents:
      - title: "Game"
        contents:
          - title: "星の守り人"
            url: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.html"
          - title: "Shooting"
            url: "/Portfolio/UnrealEngine/Game/Shooting/index.html"
          - title: "ぴの塔"
            url: "/Portfolio/UnrealEngine/Game/Roguelike/index.html"
          - title: "Maze"
            url: "/Portfolio/UnrealEngine/Game/Maze/index.html"
      - title: "Plugin"
        contents:
          - title: "SpreadSheetToUnreal"
            url: "https://github.com/pto8913/SpreadSheetToUnreal"
            type: "absolute"
          - title: "PtoTalkSystem"
            url: "/Portfolio/UnrealEngine/Plugins/PtoTalkSystem/PtoTalkSystem.html"
      - title: Note
        url: ""
  DirectX11-C++:
    url: "/Portfolio/DirectX11-C++/DirectX11_Index.html"
    contents: 
      - title: "Game"
        contents:
          - title: "とこぷよ"
            url : "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo.html"
      - title: "Plugin"
        url: "/Portfolio/UnrealEngine/Plugins/UnrealEngine_Plugin.html"
      - title: Note
        url: ""
  Unity:
    url: "/Portfolio/Unity/Unity_Index.html"
    contents:
      - title: "Game"
        contents:
          - title: "TappyCube"
            url: "/Portfolio/DirectX/Game/TappyCube/index.html"
      - title: "Plugin"
        url: "/Portfolio/UnrealEngine/Plugins/UnrealEngine_Plugin.html"
      - title: Note
        url: ""
  Java:
    url: "/Portfolio/Java/Java_Index.html"
    contents:
      - title: "Windows"
        contents:
          - title: "MusicPlayer for Windows"
            url: "/Portfolio/Java/Windows/MusicPlayer/MusicPlayer.html"

# ------------------------------ Portfolio ------------------------------
# Navigations

Hoshimori-teaser-url: "https://www.youtube.com/embed/m7YOHEtjhbc?list=PL3Z_2bfv7lRMZESwtishkG8TPBxRLmcsP"

# ---------------- Portfolio Index ----------------
News:
  星の守り人: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori"
  とこぷよ: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo"

idx-Portfolio:
  - subject: "ゲーム"
    contents:
      - title: "星の守り人"
        img: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.png"
        url: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.html"
      - title: "とこぷよ"
        img: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo.png"
        url: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo.html"
      - title: "Tappy Cube"
        img: "/Portfolio/Unity/Game/TappyCube/assets/images/icon.png"
        url: "/Portfolio/Unity/Game/TappyCube/index.html"
      - title: "Roguelike"
        img: "/Portfolio/UnrealEngine/Game/Roguelike/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Roguelike/index.html"
      - title: "Shooting"
        img: "/Portfolio/UnrealEngine/Game/Shooting/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Shooting/index.html"
      - title: "Maze"
        img: "/Portfolio/UnrealEngine/Game/Maze/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Maze/index.html"
  - subject: "プラグイン(Unreal Engine)"
    contents:
      - title: "GoogleSpreadSheetToUnreal"
        img: "/Portfolio/UnrealEngine/Plugins/SpreadSheetToUnreal/images/icon.png"
        url: "https://github.com/pto8913/SpreadSheetToUnreal"
      - title: "PtoTalkSystem"
        img: "/Portfolio/UnrealEngine/Plugins/PtoTalkSystem/assets/images/PtoTalkSystem.png"
        url: "/Portfolio/UnrealEngine/Plugins/PtoTalkSystem/PtoTalkSystem.html"
  #     - title: インベントリシステム
  #       img: "/Portfolio/Plugins/ptoInventorySystem/assets/images/icon.png"
  #       url: "/Portfolio/Plugins/ptoInventorySystem/index.html"
  - subject: "Java"
    contents:
      - title: "MusicPlayer for Windows"
        img: "/Portfolio/Java/Windows/MusicPlayer/images/icon.png"
        url: "/Portfolio/Java/Windows/MusicPlayer/MusicPlayer.html"

# ---------------- UnrealEngine Index ----------------
news-UnrealEngine:
  星の守り人: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori"

index-UnrealEngine:
  - subject: "Game"
    contents:
      - title: "星の守り人"
        img: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.png"
        url: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.html"
      - title: "Roguelike"
        img: "/Portfolio/UnrealEngine/Game/Roguelike/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Roguelike/index.html"
      - title: "Shooting"
        img: "/Portfolio/UnrealEngine/Game/Shooting/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Shooting/index.html"
      - title: "Maze"
        img: "/Portfolio/UnrealEngine/Game/Maze/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Game/Maze/index.html"
  - subject: "Plugin"
    contents:
      - title: "GoogleSpreadSheetToUnreal"
        img: "/Portfolio/UnrealEngine/Plugins/SpreadSheetToUnreal/images/icon.png"
        url: "https://github.com/pto8913/SpreadSheetToUnreal"
      - title: "PtoTalkSystem"
        img: "/Portfolio/UnrealEngine/Plugins/PtoTalkSystem/assets/images/PtoTalkSystem.png"
        url: "/Portfolio/UnrealEngine/Plugins/PtoTalkSystem/PtoTalkSystem.html"
      - title: インベントリシステム
        img: "/Portfolio/UnrealEngine/Plugins/PtoInventorySystem/assets/images/icon.png"
        url: "/Portfolio/UnrealEngine/Plugins/PtoInventorySystem/index.html"
  - subject: "Note"
    contents:
      - title: "GameplayAbilities"
        url: "/"

# ---------------- Portfolio Hoshimori ----------------
nav-header-Portfolio-Hoshimori:
  ホーム: "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.html"
  物語 : "/Portfolio/UnrealEngine/Game/Hoshimori/story/index.html"
  登場人物: "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Tolemy.html"
  プレイ映像: "/Portfolio/UnrealEngine/Game/Hoshimori/capture/index.html"
  守護者の力: "/Portfolio/UnrealEngine/Game/Hoshimori/metamorphosis/index.html"
  アクション: "/Portfolio/UnrealEngine/Game/Hoshimori/action/index.html"
  敵キャラクター:
    マブリン系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Mablin.html"
    タロス系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Talos.html"
    ライオ系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Lio.html"
    ピスケ系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Pisce.html"
    リザード系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Lizard.html"
    魔法使い系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Magician.html"
    カニ系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Cancer.html"
    ドラゴン系: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Dragon.html"
    タウロス: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Taurus.html"
    レオ: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Leo.html"
    ヴァルゴ: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Virgo.html"
    魔王: "/Portfolio/UnrealEngine/Game/Hoshimori/enemy/Typhon.html"
  UI: "/Portfolio/UnrealEngine/Game/Hoshimori/ui/index.html"
  レベルデザイン: "/Portfolio/UnrealEngine/Game/Hoshimori/level/index.html"

# ---------------- DirectX Index ----------------
news-DirectX:
  とこぷよ: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo"

index-DirectX:
  - subject: "Game"
    contents:
      - title: "とこぷよ"
        img: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo.png"
        url: "/Portfolio/DirectX/Game/TokoPuyo/TokoPuyo.html"

# ---------------- Unity Index ----------------
news-Unity:
  Tappy Cube: "/Portfolio/Unity/Game/TappyCube/index"

index-Unity:
  - subject: "Game"
    contents:
      - title: "Tappy Cube"
        img: "/Portfolio/Unity/Game/TappyCube/assets/images/icon.png"
        url: "/Portfolio/Unity/Game/TappyCube/index.html"

# ---------------- Java Index ----------------
news-Java:
  MusicPlayer for Windows: "/Portfolio/Java/Windows/MusicPlayer/MusicPlayer"

index-Java:
  - subject: "Windows"
    contents:
      - title: "MusicPlayer for Windows"
        img: "/Portfolio/Java/Windows/MusicPlayer/images/icon.png"
        url: "/Portfolio/Java/Windows/MusicPlayer/MusicPlayer.html"

# ---------------- PyQt5 Index ----------------
index-PyQt5:
  - subject: "App"
    contents:
      - title: "画面のキャプチャ"
        img: "/Portfolio/PyQt5/Tools/ScreenCapture/icon.png"
        url: "/Portfolio/PyQt5/Tools/ScreenCapture/ScreenCapture.html"
      - title: "時計"
        img: "/Portfolio/PyQt5/Tools/Timer/icon.png"
        url: "/Portfolio/PyQt5/Tools/Timer/Timer.html"
      - title: "電卓"
        img: "/Portfolio/PyQt5/Tools/Calculator/icon.png"
        url: "/Portfolio/PyQt5/Tools/Calculator/Calculator.html"
      - title: "Clipboard"
        url: "/Portfolio/PyQt5/Tools/Clipboard/Clipboard.html"
      - title: "DirViewr"
        url: "/Portfolio/PyQt5/Tools/DirViewr/DirViewr.html"
      - title: "img2pdf"
        url: "/Portfolio/PyQt5/Tools/img2pdf/img2pdf.html"
      - title: "SQLiteViewer"
        url: "/Portfolio/PyQt5/Tools/SQLiteViewer/SQLiteViewer.html"
      - title: "SQLiteViewerDetails"
        url: "/Portfolio/PyQt5/Tools/SQLiteViewerDetails/SQLiteViewerDetails.html"
      - title: "TerrainViewer"
        url: "/Portfolio/PyQt5/Tools/TerrainViewer/TerrainViewer.html"
  - subject: "PyQt5のテンプレート？"
    contents:
      - title: "コピー"
        img: "/Portfolio/PyQt5/Template/Clipboard/icon.png"
        url: "/Portfolio/PyQt5/Template/Clipboard/Clipboard.html"
      - title: "ドラッグアンドドロップ"
        img: "/Portfolio/PyQt5/Template/DnD/icon.png"
        url: "/Portfolio/PyQt5/Template/DnD/DnD.html"
      - title: "スレッド"
        img: "/Portfolio/PyQt5/Template/Thread/icon.png"
        url: "/Portfolio/PyQt5/Template/Thread/Thread.html"
      - title: "ディレクトリツリー"
        img: "/Portfolio/PyQt5/Template/DirViewer/icon.png"
        url: "/Portfolio/PyQt5/Template/DirViewer/DirViewer.html"
      # - title: "キーの同時入力"
      #   img: "/Portfolio/PyQt5/Template/keyPressMulti/icon.png"
      #   url: "/Portfolio/PyQt5/Template/keyPressMulti/keyPressMulti.html"

# ---------------- KyoPro Index ----------------
index-KyoPro:
  - subject: "競プロのサイト"
    contents:
      - title: "AtCoder"
        url: https://atcoder.jp/?lang=ja
        type: "absolute" 
      - title: "CodeForces"
        url: https://codeforces.com/
        type: "absolute" 
  - subject: "動的計画法"
    contents:
      - title: "累積和"
        url: "/Portfolio/KyoPro/DP/CumulativeSum.html"
  - subject: "データ構造"
    contents:
      - title: "素集合データ構造(Union-Find)"
        url: "/Portfolio/KyoPro/Structure/UnionFind.html"
      - title: "BinaryIndexedTree(BIT)"
        url: "/Portfolio/KyoPro/Structure/BIT.html"
  - subject: "探索"
    contents:
      - title: "深さ優先探索(DFS)"
        url: "/Portfolio/KyoPro/Search/DFS.html"
      - title: "幅優先探索(BFS)"
        url: "/Portfolio/KyoPro/Search/BFS.html"
  - subject: "最短経路探索"
    contents:
      - title: "ダイクストラ法(Dijkstra)"
        url: "/Portfolio/KyoPro/Search/Dijkstra.html"
      - title: "ベルマンフォード法"
        url: "/Portfolio/KyoPro/Search/BellmanFord.html"
  - subject: "最短経路探索"
    contents:
      - title: "約数列挙(Divisor)"
        url: "/Portfolio/KyoPro/Math/divisor.html"
      - title: "素数判定(isprime)"
        url: "/Portfolio/KyoPro/Math/isprime.html"
      - title: "最大公約数(gcd)最小公倍数(lcm)"
        url: "/Portfolio/KyoPro/Math/gcdlcm.html"

# ------------------------------ Hoshimori ------------------------------
# Images

hoshimori-character:
  ベータ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Beta"
  トレミー : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Tolemy"
  アルファ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Alpha"
  アリエ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Arie"
  リブラ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Libra"
  エルダ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Elda"
  タウロス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Taurus"
  ヴァルゴ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Virgo"
  レオ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Leo"
  ピス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Pis"
  アクア : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Aqua"
  ケス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Ces"
  ステラ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Stella"

img-hoshimori-character-bg:
  ホーム : "/Portfolio/UnrealEngine/Game/Hoshimori/Hoshimori.png"
  ベータ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Beta.png"
  トレミー : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Tolemy.png"
  アルファ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Alpha.png"
  アリエ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Arie.png"
  リブラ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Libra.png"
  エルダ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Elda.png"
  タウロス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Taurus.png"
  ヴァルゴ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Virgo.png"
  レオ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Leo.png"
  ピス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_PisCes.png"
  アクア : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Aqua.png"
  ケス : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_PisCes.png"
  ステラ : "/Portfolio/UnrealEngine/Game/Hoshimori/Characters/Background_Aqua.png"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/