# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#encoding: utf-8

title: pto8913
author: pto8913
#email: your-email@example.com
#>- # this means to ignore newlines until "baseurl:"
description: 制作物や知見を置いていく場所
twitter_username: pitodesu
github_username: pto8913


lang: "jp"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

markdown: kramdown

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
future: true
published: true

permalink: /:categories/:title.html
permalink_pattern: /:dir/:categories/:title.html


baseURL: "https://pto8913.github.io/pto8913/"
KyoProURL: "https://pto8913.github.io/pto8913/KyoPro"
PyQtURL: "https://pto8913.github.io/pto8913/PyQt5"
UEURL: "https://pto8913.github.io/pto8913/UE4"
HoshimoriURL: "https://pto8913.github.io/pto8913/Hoshimori"

github: [metadata]
repository: pto8913.github.io/pto8913

# Build settings
# remote_theme: niklasbuschmann/contrast
theme: minima
highlighter: rouge
#theme: jekyll-theme-architect

paginate: 5
paginate_path: "/pto8913/page:num/"


plugins:
  - jekyll-feed
  # - jekyll-remote-theme
  #- jekyll-github-metadata

# Menu

# Navigations
nav-header:                # accepts {file, title, url, icon, sidebaricon}
  ホーム: "/"
  ポートフォリオ: "/Portfolio/index.html"

nav-footer:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Gmail, icon: '/assets/images/gmail.png', url: "mailto:pto8913project@gmail.com"}
  - {title: Github, icon: '/assets/images/github.png', url: "https://github.com/pto8913"}
  - {title: HatenaBlog, icon: '/assets/images/hatenablog.png', url: "https://pto8913.hatenablog.com/"}

# ------------------------------ Portfolio ------------------------------
# Navigations

nav-header-Portfolio:
  ホーム: "/Portfolio/index.html"
# ---------------- Portfolio Index ----------------
idx-Portfolio:
  - subject: "ゲーム"
    contents:
      - title: "星の守り人"
        img: "/Hoshimori/assets/images/T_Title.png"
        url: "/Portfolio/Hoshimori/index.html"
  - subject: "PyQt5"
    contents:
      - title: "画面のキャプチャ"
        img: "/Portfolio/PyQt5/Tools/ScreenCapture/icon.png"
        url: "/Portfolio/PyQt5/Tools/ScreenCapture/ScreenCapture.html"
      - title: "時計"
        img: "/Portfolio/PyQt5/Tools/Timer/icon.png"
        url: "/Portfolio/PyQt5/Tools/Timer/Timer.html"
      - title: "電卓"
        img: "/Portfolio/PyQt5/Tools/Calculator/icon.png"
        url: "/Portfolio/PyQt5/Tools/Calculator/Calculator.html"
  - subject: "PyQt5のテンプレート？"
    contents:
      - title: "コピー"
        img: "/Portfolio/PyQt5/Template/Clipboard/icon.png"
        url: "/Portfolio/PyQt5/Template/Clipboard/Clipboard.html"
      - title: "ドラッグアンドドロップ"
        img: "/Portfolio/PyQt5/Template/DnD/icon.png"
        url: "/Portfolio/PyQt5/Template/DnD/DnD.html"
      - title: "スレッド"
        img: "/Portfolio/PyQt5/Template/Thread/icon.png"
        url: "/Portfolio/PyQt5/Template/Thread/Thread.html"
      - title: "ディレクトリツリー"
        img: "/Portfolio/PyQt5/Template/DirViewer/icon.png"
        url: "/Portfolio/PyQt5/Template/DirViewer/DirViewer.html"
      # - title: "キーの同時入力"
      #   img: "/Portfolio/PyQt5/Template/keyPressMulti/icon.png"
      #   url: "/Portfolio/PyQt5/Template/keyPressMulti/keyPressMulti.html"
  # - subject: "競プロ"
  #   contents:
  #     - title: "競プロ"
  #       url: "/Portfolio/KyoPro/index.html"

# ---------------- Portfolio Hoshimori ----------------
nav-header-Portfolio-Hoshimori:
  ホーム: "/Portfolio/Hoshimori/index.html"
  守護者の力: "Portfolio/Hoshimori/metamorphosis/index.html"
  アクション:
    登る: "Portfolio/Hoshimori/action/Climbing.html"
    釣り: "Portfolio/Hoshimori/action/Fishing.html"
    アイテムを拾う: "Portfolio/Hoshimori/action/Pickup.html"
    ボタンを押す: "Portfolio/Hoshimori/action/Press.html"
    押す: "Portfolio/Hoshimori/action/Push.html"
    休む: "Portfolio/Hoshimori/action/Rest.html"
    泳ぐ: "Portfolio/Hoshimori/action/Swimming.html"
    会話: "Portfolio/Hoshimori/action/Talk.html"
    乗り物: "Portfolio/Hoshimori/action/Vehicle.html"
  敵キャラクター:
    マブリン系: "Portfolio/Hoshimori/enemy/Mablin.html"
    タロス系: "Portfolio/Hoshimori/enemy/Talos.html"
    ライオ系: "Portfolio/Hoshimori/enemy/Lio.html"
    ピスケ系: "Portfolio/Hoshimori/enemy/Pisce.html"
    リザード系: "Portfolio/Hoshimori/enemy/Lizard.html"
    魔法使い系: "Portfolio/Hoshimori/enemy/Magician.html"
    カニ系: "Portfolio/Hoshimori/enemy/Cancer.html"
    ドラゴン系: "Portfolio/Hoshimori/enemy/Dragon.html"
    タウロス: "Portfolio/Hoshimori/enemy/Taurus.html"
    レオ: "Portfolio/Hoshimori/enemy/Leo.html"
    ヴァルゴ: "Portfolio/Hoshimori/enemy/Virgo.html"
    魔王: "Portfolio/Hoshimori/enemy/Typhon.html"
  UI:
    タイトルUI: "/Portfolio/Hoshimori/ui/title.html"
    チュートリアルUI: "/Portfolio/Hoshimori/ui/tutorial.html"
    HUD: "/Portfolio/Hoshimori/ui/hud.html"
    かばんUI: "/Portfolio/Hoshimori/ui/belongings.html"
    戦闘UI: "/Portfolio/Hoshimori/ui/battle.html"
    NPCとの会話UI: "/Portfolio/Hoshimori/ui/talk.html"
    カメラUI: "/Portfolio/Hoshimori/ui/camera.html"
    釣りUI: "/Portfolio/Hoshimori/ui/fishing.html"
    休むUI: "/Portfolio/Hoshimori/ui/rest.html"
    ローディングUI: "/Portfolio/Hoshimori/ui/loading.html"
  レベルデザイン:
    聖域: "/Portfolio/Hoshimori/level/Sanctuary.html"
    天望島: "/Portfolio/Hoshimori/level/RegionTenbou.html"
    カトラス島: "/Portfolio/Hoshimori/level/RegionCatlas.html"
    ルコス地方: "/Portfolio/Hoshimori/level/RegionLkos.html"
    ラーボ地方: "/Portfolio/Hoshimori/level/RegionLabo.html"
    シラージェ火山: "/Portfolio/Hoshimori/level/RegionSillarje.html"
    グラム谷: "/Portfolio/Hoshimori/level/RegionGlam.html"
    アクア団基地: "/Portfolio/Hoshimori/level/RegionWasser.html"
  プレイ映像: "Portfolio/Hoshimori/capture/index.html"

# ------------------------------ Hoshimori ------------------------------
# Navigations

nav-header-Hoshimori:
  ホーム: "/Hoshimori/index.html"
  物語: "/Hoshimori/story.html"
  登場人物: "Hoshimori/Characters/Tolemy.html"
  ゲーム紹介: "/Hoshimori/description.html"

nav-footer-Hoshimori:
  - {title: Youtube, icon: '/assets/images/youtube.png', url: "https://www.youtube.com/@Hosinomoribito_JP"}
  - {title: Discord, icon: '/assets/images/discord.png', url: "https://discord.gg/mXntvZdCFf"}

# Images

hoshimori-character:
  ベータ : "/Hoshimori/Characters/Beta"
  トレミー : "/Hoshimori/Characters/Tolemy"
  アルファ : "/Hoshimori/Characters/Alpha"
  アリエ : "/Hoshimori/Characters/Arie"
  リブラ : "/Hoshimori/Characters/Libra"
  エルダ : "/Hoshimori/Characters/Elda"
  タウロス : "/Hoshimori/Characters/Taurus"
  ヴァルゴ : "/Hoshimori/Characters/Virgo"
  レオ : "/Hoshimori/Characters/Leo"
  ピス : "/Hoshimori/Characters/Pis"
  アクア : "/Hoshimori/Characters/Aqua"
  ケス : "/Hoshimori/Characters/Ces"
  ステラ : "/Hoshimori/Characters/Stella"
img-hoshimori-character-bg:
  ホーム : "/Hoshimori/assets/images/T_Title.png"
  ベータ : "/Hoshimori/Characters/Background_Beta.png"
  トレミー : "/Hoshimori/Characters/Background_Tolemy.png"
  アルファ : "/Hoshimori/Characters/Background_Alpha.png"
  アリエ : "/Hoshimori/Characters/Background_Arie.png"
  リブラ : "/Hoshimori/Characters/Background_Libra.png"
  エルダ : "/Hoshimori/Characters/Background_Elda.png"
  タウロス : "/Hoshimori/Characters/Background_Taurus.png"
  ヴァルゴ : "/Hoshimori/Characters/Background_Virgo.png"
  レオ : "/Hoshimori/Characters/Background_Leo.png"
  ピス : "/Hoshimori/Characters/Background_Pis.png"
  アクア : "/Hoshimori/Characters/Background_Aqua.png"
  ケス : "/Hoshimori/Characters/Background_Ces.png"
  ステラ : "/Hoshimori/Characters/Background_Stella.png"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/